/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { LayoutImport } from "./../../../pages/router"
import { R404Import } from "./../../../pages/router"
import { BookImport } from "./../../../pages/router"
import { InitialImport } from "./../../../pages/router"
import { DebugImport } from "./../../../pages/router"
import { AboutImport } from "./../../../pages/router"
import { CatalogImport } from "./../../../pages/router"

const InitialRoute = InitialImport.update({
   path: "/",
   getParentRoute: () => LayoutImport,
   // biome-ignore lint/suspicious/noExplicitAny: <explanation>
} as any)

const R404Route = R404Import.update({
   id: "/__404",
   path: "/*",
   getParentRoute: () => LayoutImport,
   // biome-ignore lint/suspicious/noExplicitAny: <explanation>
} as any)

const BookRoute = BookImport.update({
   path: "/book/$bookId",
   getParentRoute: () => LayoutImport,
   // biome-ignore lint/suspicious/noExplicitAny: <explanation>
} as any)

const DebugRoute = DebugImport.update({
   path: "/debug",
   getParentRoute: () => LayoutImport,
   // biome-ignore lint/suspicious/noExplicitAny: <explanation>
} as any)

const AboutRoute = AboutImport.update({
   path: "/about",
   getParentRoute: () => LayoutImport,
   // biome-ignore lint/suspicious/noExplicitAny: <explanation>
} as any)

const CatalogRoute = CatalogImport.update({
   path: "/catalog",
   getParentRoute: () => LayoutImport,
   // biome-ignore lint/suspicious/noExplicitAny: <explanation>
} as any)

declare module "@tanstack/react-router" {
   interface FileRoutesByPath {
      "/": {
         preLoaderRoute: typeof string
         parentRoute: typeof LayoutImport
      }
      "/__404": {
         preLoaderRoute: typeof string
         parentRoute: typeof LayoutImport
      }
      "/book/$bookId": {
         preLoaderRoute: typeof string
         parentRoute: typeof LayoutImport
      }
      "/about": {
         preLoaderRoute: typeof string
         parentRoute: typeof LayoutImport
      }
      "/catalog": {
         preLoaderRoute: typeof string
         parentRoute: typeof LayoutImport
      }
      "/debug": {
         preLoaderRoute: typeof string
         parentRoute: typeof LayoutImport
      }
   }
}

export const routeTree = LayoutImport.addChildren([
   InitialRoute,
   BookRoute,
   AboutRoute,
   CatalogRoute,
   R404Route,
   DebugRoute,
])

/* prettier-ignore-end */
